_BASE_: "faster_rcnn_R_101_FPN_ETF_pre3_2shot.yaml"
MODEL:
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
  ROI_HEADS:
    NAME: "DistillMarginROIHeads"
LOSS:
  ADJUST_STAGE: 'distill'
OUTPUT_DIR: "checkpoints/voc/distill/t1"