_BASE_: "faster_rcnn_R_101_FPN_ETF_pre1_3shot.yaml"
MODEL:
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
  ROI_HEADS:
    NAME: "DistillMarginROIHeads"
LOSS:
  ADJUST_STAGE: 'distill'
SOLVER:
  BASE_LR: 0.04
# Using 0.04 is slightly better than 0.02
OUTPUT_DIR: "checkpoints/voc/distill/t1"