_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 20
    OUTPUT_LAYER: "FastRCNNOutputETFLayers"
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval_allnovel1_2shot', 'voc_2007_trainval_allbase1', 'voc_2012_trainval_allbase1')
  TEST: ('voc_2007_test_all1',)
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.05
LOSS:
  TERM: "adjustment"
  ADJUST_BACK: 5000.0
  ADJUST_MODE: 'multiply'
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (12000, 16000)
  MAX_ITER: 20000
  WARMUP_ITERS: 200
  BASE_LR: 0.02
TEST:
  EVAL_PERIOD: 3000
RESETOUT: True
OUTPUT_DIR: "checkpoints/voc/prior/t1"
# ADJUST_BACK 5k > 10k > 1k (fixed)
# REPEAT_THRESHOLD 0.05 > 0.01 > 0.1 > 0.005 > 0.2 (0.1 under determination)